import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import Navbar from '@/components/navbar/Navbar'
import { AuthProvider } from "@/context/AuthContext";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Music Hub ",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
  applicationName: "Music Hub",
  authors: {
    name: "Swapnil Ingle",
    url: "https://github.com/codersHub-in",

  },

  creator: "Swapnil Ingle",
  publisher: "Swapnil Ingle",
  formatDetection: {
    telephone: true,
    address: true,
  },
  keywords: ["music", "music hub", "music player", "music player", "music player", "music player", "music player"],
  category: "music",


};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  console.log('children:')

  return (
    <html lang="en">
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />



      <AuthProvider>
        <body className={`${inter.className}  bg-black `}>

          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Navbar className="" />
            {children}
          </ThemeProvider>
        </body>
      </AuthProvider>
    </html>
  );
}
